### PR TITLE
Consider IMCU size when rounding and viewing jpeg crops.

### PR DESCRIPTION
**Pull request by arcmags**
This commit uses imagemagick's `identify` command to determine jpeg IMCU size.

To do so, I had to import subprocess into `cropgtk.py` in order to call `identify` on each new image as it's drawn.  Also, instead of a single rounding variable `self.round` in `cropgui_common.py`, there are now two variables `self.roundW` and `self.roundH` for the respective cases.

### CODE REVIEW

**Comment by jepler** [comment]
I agree it would be great to finally obey the true iMCU boundaries instead of making a dubious assumption!

I notice that it is possible to create odd combinations of sampling with cjpeg:
~~~~
$ ppmmake '#040875' 256 256 | cjpeg -sample 1x1,2x1,1x2 > wat.jpg
$ identify -format '%[jpeg:sampling-factor]' wat.jpg
1x1,2x1,1x2
~~~~
wat

In this case, wouldn't cropgui need to use 16-pixel rounding?

I'd also *prefer* to see this functionality added to both GUIs but I won't refuse this pull request just because it fails to add it to the Tkinter one.

**Comment by jepler** [comment]
This info is available in PIL, I checked in python-imaging 1.1.7 and python-pil 2.6.2 (debian wheezy and jessie)
~~~~
>>> i = PIL.Image.open("wat.jpg")
>>> i.layer
[('\x01', 1, 1, 0), ('\x02', 2, 1, 1), ('\x03', 1, 2, 1)]
~~~~
so perhaps the shell out to `identify` can be avoided in this case!

**Comment by xiota** [comment]
Presumably addresses issue https://github.com/jepler/cropgui/issues/31.

However, unnecessarily complicates program because `jpegtran` already considers iMCU.

**Comment by jepler** [comment]
@xiota the thing is that the GUI *attempts* to preview the effect of snapping to iMCU boundaries, but often fails to do so.

**Comment by jepler** [comment]
Hi.  Thanks for your contribution, though due to my negligence cropgui has changed too much in the meantime to let this PR be merged.

**Pull request closed without merging**
