### PR TITLE
install prerequisites in install.sh

### PR DESCRIPTION
**Pull request by JoKalliauer**
improves #90 (related to #89)

### CODE REVIEW

**Review by jepler — COMMENTED** [review]
I'm open to others' thoughts, but I'm reluctant to take this change.

I don't like the idea of unconditionally doing actions in the packaging system when invoking install.sh.  I also think this will actually break the (undocumented, but apparently working) Debian package bulding process which invokes ./install.sh itself; running apt during package building is not going to work.

(The debian package building process is easy: `sudo apt install build-essential devscripts equivs; mk-build-deps -irs sudo; debuild`; the first two steps are only required once.  Then you can install the package so that it can be later removed/upgraded easily: `dpkg -i ../cropgui_${VERSION}_all.deb`)

I'd be happy to see these lines added to a new *install_deps.sh* (or similar name file) and documented in the README, since runnable code beats code to copy & paste; how do you feel about that?

**Comment by zvezdochiot** [comment]
🛑 You can't do that! Dependencies are specified in `requirements.txt`! The above construction is unacceptable!

**Comment by jepler** [comment]
Right now, cropgui doesn't use "standard" Python packaging.  When I originally wrote it, my personal preferences led me to prefer Debian packaging, so there's no setup.py, requirements.txt, etc. (even recently, 've had problems with Python programs that try to install GUI toolkits via pip, but perhaps that is not the experience of the majority of folks--namely, qt5 on debian buster does not seem to work, because it downloads binary packages that do not match debian closely enough in shared library naming)

That said, @zvezdochiot, I'd be happy to consider pull requests to make cropgui work better with standard Python packaging.  I think it would benefit a pretty big group of potential users to have the installation process be "pip install cropgui".  Would you consider helping us with this?

**Comment by zvezdochiot** [comment]
Sorry. I would be glad, but I don't work with pip, as well as installation scripts. There was no need for the first, the second is simply inappropriate. I myself use debian packages. If I need my own assembly, I do it manually: https://github.com/BASH-Auto-Tools/bash-deb-build

**Pull request closed without merging**
