### PR TITLE
Support multiple image types using ImageMagick convert

### PR DESCRIPTION
**Pull request by rafaqz**
I realised half the time I actually need a simple crop tool for pngs. But it may as well just support all formats as it's no extra work.

I split the command building process and swapped the stdout form of jpegtrans for the -outfile flag
so it's more similar to convert. I'm not sure how that will affect cropgui.py if it uses cropgui_common.py, it wont run for me anyway.

Mixed in is a fix for not ending up with files titled image-crop-crop-crop.jpg from multiple edits. it's limited to one -crop then it just overwrites the file. This probably could be a separate pull request but it depends on not using stdout.

### CODE REVIEW

**Comment by jepler** [comment]
Unfortunately, this pull request now conflicts due to another older pull request I just accepted.  Can you fix and resubmit?

**Comment by rafaqz** [comment]
The @onno74 merge breaks cropping after rotation. My pull request needed cleaning up anyway so happy to put in a new request, but It's probably best to fix the problems before merging more on top of them.

**Comment by onno74** [comment]
Sorry for this. I did not use or care about cropgtk.py at all. I used cropgui.py, which has no rotation.
Unfortunately I broke cropgtk.py complely (not just the rotation). @reubot fixed most of it, but apparently not the cropping after rotation.

**Comment by rafaqz** [comment]
That makes sense, I noticed your commits in cropgui.py

I think my pull request might break cropgui.py! I'll do some testing to
make sure it doesn't.

**Comment by onno74** [comment]
I've just committed a two line fix for cropping after rotation. I'll make a pull request now.

**Comment by jepler** [comment]
Personally I use the gtk front-end exclusively.  I have considered removing the other, but clearly I should not.  It is also my fault that I merged that pull request without sufficient testing.

**Comment by rafaqz** [comment]
I was wondering if they could move towards being separate projects? it does
invite problems like this and adds an abstraction layer to the code.

**Comment by onno74** [comment]
For me, the reason to modify only cropgui.py was, that while I don't speak python and don't know gtk, I found it easier to figure out how to add menus in cropgui.py than in cropgtk.py. I would be ok with removing cropgui.py if someone ported fixed-size-cropping to cropgtk.py.

**Comment by jepler** [comment]
And unfortunately cropgui's gtk window layout is trapped in an old version of glade that is no longer supported, making it even more difficult to move forward in that direction.

**Pull request closed without merging**
