### PR TITLE
Try tostring(), fall back to tobytes()

### PR DESCRIPTION
**Pull request by tstenner**

### CODE REVIEW

**Comment by jepler** [comment]
" When catching exceptions, mention specific exceptions whenever possible instead of using a bare except: clause. "  https://www.python.org/dev/peps/pep-0008/

Accepting but I'd be pleased if you would revise the code to follow PEP 8's recommendation.  Probably it should read 'except AttributeError:'.

**Comment by tstenner** [comment]
Unfortunately, this isn't possible as Pillow>=3.0 defines tostring() as follows:
<pre><code>def tostring(self, *args, **kw):
    raise Exception("tostring() has been removed. " +
                    "Please call tobytes() instead.")
</code></pre>

**Comment by jepler** [comment]
wow, that is terrible.  thanks.

**Comment by jepler** [comment]
could use LBYL pattern.  untested:
~~~~
def tobytes(image):
    if hasattr(image, 'tobytes'): return image.tobytes()
    else: return image.tostring()

...
image_data = tobytes(rendered)
~~~~

**Pull request merged**
